---
- name: Converge
  hosts: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1
  roles:
    - role: ../roles/elastic-stack/ansible-elasticsearch
      elasticsearch_network_host: 0.0.0.0
      elasticsearch_reachable_host: 127.0.0.1
      elasticsearch_node_name: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1
      single_node: false
      elasticsearch_master_candidate: true
      elasticsearch_bootstrap_node: true
      elasticsearch_cluster_nodes:
        - elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1
      elasticsearch_discovery_nodes:
        - elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1
        - elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-2
      elasticsearch_lower_disk_requirements: true
      elasticsearch_xpack_security: true
      elasticsearch_xpack_security_user: elastic
      elasticsearch_xpack_security_password: elastic_pass
      node_certs_generator: true
      node_certs_generator_ip: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1
      master_certs_path: /tmp/xpack-certs
      generate_CA: true
      ca_key_name: "wazuh-test"
      ca_cert_name: "wazuh-cert"
      ca_password: "test-password"

  vars:
    instances:
      elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1:
        name: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1
        dns: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1
      elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-2:
        name: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-2
        dns: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-2

- hosts: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-2
  roles:
    - role: ../roles/elastic-stack/ansible-elasticsearch
      elasticsearch_network_host: 0.0.0.0
      elasticsearch_reachable_host: 127.0.0.1
      elasticsearch_node_name: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-2
      single_node: false
      elasticsearch_master_candidate: true
      elasticsearch_discovery_nodes:
        - elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1
        - elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-2
      elasticsearch_lower_disk_requirements: true
      elasticsearch_xpack_security: true
      elasticsearch_xpack_security_user: elastic
      elasticsearch_xpack_security_password: elastic_pass
      node_certs_generator_ip: elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}-1
      master_certs_path: /tmp/xpack-certs
      generate_CA: true
      ca_key_name: "wazuh-test"
      ca_cert_name: "wazuh-cert"
      ca_password: "test-password"
  vars:
    elasticsearch_xpack_users:
      molecule_user:
        password: 'MoleculePassword'
        roles: '["superuser"]'
