---
dependency:
  name: galaxy
driver:
  name: docker
  #lint:
  #  name: yamllint
lint:
  name: yamllint
  enabled: false
  options:
    config-data:
      ignore: .virtualenv
platforms:
  #- name: wazuh_server_centos7
  #  image: milcom/centos7-systemd
  #  networks:
  #    - name: wazuh
  #  privileged: true
  #  groups:
  #    - manager
  - name: wazuh_agent_${MOL_PLATFORM:-centos7}
    image: ${MOL_IMAGE:-paulfantom/centos-molecule:7}
    pre_build_image: true
    networks:
      - name: wazuh
    groups:
      - agent
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #- name: wazuh_agent_xenial
  #  image: solita/ubuntu-systemd:xenial
  #  privileged: true
  #  command: /sbin/init
  #  networks:
  #    - name: wazuh
  #  groups:
  #    - agent
  #- name: wazuh_agent_trusty
  #  image: ubuntu:trusty
  #  networks:
  #    - name: wazuh
  #  groups:
  #    - agent
  #- name: wazuh_agent_centos6
  #  image: centos:6
  #  networks:
  #    - name: wazuh
  #  groups:
  #    - agent
  #- name: wazuh_agent_centos7
  #  image: milcom/centos7-systemd
  #  privileged: true
  #  networks:
  #    - name: wazuh
  #  groups:
  #    - agent
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    docker:
      create: ../default/create.yml
      destroy: ../default/destroy.yml
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    group_vars:
      agent:
        api_pass: password
        wazuh_manager:
          address: "{{ wazuh_manager_ip }}"
          port: 1514
          protocol: udp
          api_port: 55000
          api_proto: 'http'
          api_user: null
        wazuh_agent_authd:
          authd_address: "{{ wazuh_manager_ip }}"
          enable: true
          port: 1515
          ssl_agent_ca: null
          ssl_agent_cert: null
          ssl_agent_key: null
          ssl_auto_negotiate: 'no'
  lint:
    name: ansible-lint
    enabled: true
verifier:
  name: testinfra
  lint:
    name: flake8
