Project path: "../../tests/integration"

Output path: "../output"

Include paths:
  - "../../tests/integration/test_wazuh_db"
  - "../../tests/integration/test_vulnerability_detector"

Include regex:
  - "^test_.*py$"

Group files:
  - "README.md"

Function regex:
  - "^test_"

Ignore paths:
  - "../../tests/integration/test_wazuh_db/data"

Output fields:
  Module:
    Mandatory:
      - brief
      - metadata:
        - modules
        - daemons
        - component
        - operating_system
        - tiers
    Optional:
      - tags
  Test:
    Mandatory:
      - test_logic
      - checks
    Optional:
      - expected_result
      - test_cases

Test cases field: test_cases
