Project path: "../../tests/integration"

Output path: "../output"

Include paths:
  - "../../tests/integration/test_active_response"
  - "../../tests/integration/test_agentd"
  - "../../tests/integration/test_analysisd"
  - "../../tests/integration/test_api"
  - "../../tests/integration/test_authd"
  - "../../tests/integration/test_cluster"

Include regex:
  - "^test_.*py$"

Group files:
  - "README.md"

Function regex:
  - "^test_"

Ignore paths:
  - "../../tests/integration/test_active_response/test_analysisd/data"
  - "../../tests/integration/test_active_response/test_execd/data"
  - "../../tests/integration/test_agentd/data"
  - "../../tests/integration/test_analysisd/test_all_syscheckd_configurations/data"
  - "../../tests/integration/test_analysisd/test_all_syscheckd_configurations/yaml_generators"
  - "../../tests/integration/test_analysisd/test_error_messages/data"
  - "../../tests/integration/test_analysisd/test_event_messages/data"
  - "../../tests/integration/test_analysisd/test_integrity_messages/data"
  - "../../tests/integration/test_analysisd/test_mitre/data"
  - "../../tests/integration/test_analysisd/test_scan_messages/data"
  - "../../tests/integration/test_api/test_config/test_bruteforce_blocking_system/data"
  - "../../tests/integration/test_api/test_config/test_cache/data"
  - "../../tests/integration/test_api/test_config/test_cors/data"
  - "../../tests/integration/test_api/test_config/test_DOS_blocking_system/data"
  - "../../tests/integration/test_api/test_config/test_drop_privileges/data"
  - "../../tests/integration/test_api/test_config/test_experimental_features/data"
  - "../../tests/integration/test_api/test_config/test_host_port/data"
  - "../../tests/integration/test_api/test_config/test_https/data"
  - "../../tests/integration/test_api/test_config/test_jwt_token_exp_timeout/data"
  - "../../tests/integration/test_api/test_config/test_logs/data"
  - "../../tests/integration/test_api/test_config/test_rbac/data" 
  - "../../tests/integration/test_api/test_config/test_request_timeout/data"
  - "../../tests/integration/test_api/test_config/test_use_only_authd/data"
  - "../../tests/integration/test_authd/data"
  - "../../tests/integration/test_cluster/test_key_polling/data"

Output fields:
  Module:
    Mandatory:
      - copyright
      - type
      - brief
      - tier
      - modules
      - components
      - daemons
      - os_platform
      - os_version
    Optional:
      - references
      - pytest_args
      - tags
  Test:
    Mandatory:
      - description
      - wazuh_min_version
      - parameters
      - assertions
      - inputs
      - input_description
      - expected_output
    Optional:
      - tags

Test cases field: inputs
