---
- name: Converge
  hosts: all
  roles:
    - role: wazuh/ansible-wazuh-manager
      vars:
        wazuh_manager_config:
            cluster:
                disable: 'no'
                name: 'wazuh'
                node_name: 'worker-01'
                node_type: 'worker'
                key: 'ugdtAnd7Pi9myP7CVts4qZaZQEQcRYZa'
                port: '1516'
                bind_addr: '0.0.0.0'
                nodes:
                - "manager_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}"
                hidden: 'no'
    - { role: wazuh/ansible-filebeat, filebeat_output_elasticsearch_hosts: "elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}:9200" }


