---

    - name: restart wazuh manager
      systemd:
        state: restarted
        name: wazuh-manager
    
    - name: restart wazuh agent
      systemd:
        state: restarted
        name: wazuh-agent
    
    - name: restart wazuh agent windows
      win_service:
        name: OssecSvc
        start_mode: auto
        state: restarted