---
- hosts: all
  tasks:
  - name: Check if dest_folder exists
    file: path="/{{ dest_folder }}" state=directory

  - name: copy test folder on instance
    copy:
      src: "{{ src_folder }}/"
      dest: "/{{ dest_folder }}/"
