---
- name: Converge
  hosts: manager_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}
  roles:
    - role: wazuh/ansible-wazuh-manager
      vars:
        wazuh_manager_config:
            cluster:
                disable: 'no'
                name: 'wazuh'
                node_name: 'manager'
                node_type: 'master'
                key: 'ugdtAnd7Pi9myP7CVts4qZaZQEQcRYZa'
                port: '1516'
                bind_addr: '0.0.0.0'
                nodes:
                - "manager_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}"
                hidden: 'no'
    - { role: wazuh/ansible-filebeat, filebeat_output_elasticsearch_hosts: "elasticsearch_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}:9200" }

- hosts: agent_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}
  roles:
    - role: wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: "manager_{{ lookup('env', 'MOL_PLATFORM') or 'centos7' }}"
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
    wazuh_agent_authd:
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'
